### PR TITLE
Add support to prefix

### PR DESCRIPTION
**Pull request by rodrigowirth**
It will allow to set a prefix and allow to run a server index behind a proxy for example

### CODE REVIEW

**Comment by rodrigowirth** [comment]
I am going to fix the issues with old node versions.

**Comment by ntomsic** [comment]
Would love to have this in

**Comment by rodrigowirth** [comment]
This PR is ready for reviewing.

@ntomsic @dougwilson

**Comment by dougwilson** [comment]
Sorry I didn't see this before. If you are behind a proxy this is not the only module you're going to have issue with. Anything trying to get the full URL including for redirects will have issues. Your app should be adding to prefix to req.originalUrl such that everything (including this module) will understand the prefix transparently.

**Pull request closed without merging**
