### PR TITLE
Add custom date-time format feature

### PR DESCRIPTION
**Pull request by emilioplatzer**
I suggest to include the ability of define the way for custom date-time format. 

Simply adding a dateTimeToString hook

Thanks

Emilio
PD: I also add a test and a README section

### CODE REVIEW

**Comment by dougwilson** [comment]
Seems OK. Can you provide a use-case? The test and the example in there doesn't help me picture a true use-case is all :) Effort may better be put towards implementing #20 instead of adding more and more overrides as well.

**Comment by emilioplatzer** [comment]
I think you are right. I prefer to do something more general. 

**Real case of use of date format:** I'm Spanish speaker (I'm live in Argentina). 
My server serves pages world wide. In Latin America the date format was `dd/mm/yyyy`. 
In English you expect `mm/dd/yyyy`. This does not depends of the server locate.

Now. Thinking in it more deeply I have other **Real case of use**. 

I am writing a server for developers https://github.com/codenautas/fast-devel-server with these features:
 * Render the static file contents with *auto refresh*: when you modify the source you see the new content without need of press F5 (implemented)
 * Render file index (with serve-index) with *auto refresh*: when you add a file you see the new file in the list without the need of press F5 (implemented)
 * Render markdown, jade and other templates with *auto refresh* and report of *compiler errors* when needed (not yet implemented)
 * Render file index with better info: 
   * mark which directories are github projects (with directories haves a .git subdir and a package.json file. And also mark if you can pull a newer version from github)
   * mark which files are versioned, changed or ignored

## New features for serve-index

Then I suggest (and I can do a PR with it). Add the follow hooks:
 * fileLine2html(file) 
   * called when render each line
   * returns string with HTML line
   * receives a plain object with file data: name, size, mtime, type, others
 * headers2html()
   * called for render the line of headers
   * returns string with HTML line of column headers
 * addExtraInfo(files,callback)
   * called after readdir
   * receives the list of files with the standard info
   * receives a callback function to call when done
   
### Defaults

```js
serveIndex.fileLine2html = function(file){
    // ...
    return '<li><a href="'
      + escapeHtml(normalizeSlashes(normalize(path.join('/'))))
      + '" class="' + escapeHtml(classes.join(' ')) + '"'
      + ' title="' + escapeHtml(file.name) + '">'
      + '<span class="name">' + escapeHtml(file.name) + '</span>'
      + '<span class="size">' + escapeHtml(size) + '</span>'
      + '<span class="date">' + escapeHtml(date) + '</span>'
      + '</a></li>';
};

serveIndex.headers2html = function(){
  return '<li class="header">' 
      + '<span class="name">Name</span>'
      + '<span class="size">Size</span>'
      + '<span class="date">Modified</span>'
      + '</li>') : '');
}

serveIndex.addExtraInfo = function(files,callback){
  // if(err) callback(err);
  callback(null, files);
}
```

**Comment by dougwilson** [comment]
Cool, but I do not want all those hooks; I want template rendering instead, because every hook I add, there will always be another, and another and another. If we just rendered with a templating language (like ejs or hbs or something) then you can implement all that without waiting for a module like `serve-index` to all all your custom hooks (OR you can just override the `.html` right now and implement everything today).

**Comment by emilioplatzer** [comment]
I understood. I still thinking that this PR (adding the ability to format dates) is good. 

Could you include this PR or something to format dates?

**Comment by dougwilson** [comment]
So, I'm going to close this PR for now, because really this kind of addition will never end; it's not great to keep adding these magical properties to the export in general.

With the latest `master` code, there are three ways to achieve your desired output:

1. Overwrite `Date.prototype.toLocaleDateString`/`Date.prototype.toLocaleTimeString` to get the desired stringification; it essentially comes from following Apache's mod_autoindex of serving with the server's locale.
2. Overwrite the `serveIndex.html` function to do whatever you want, though you have to re-implement a lot of things, including file stats.
3. Now you can provide a `function` to the `template` option, which is similar to overwriting the `serveIndex.html` function, but much, much easier to implement, as it provides you an array of files with all the stats objects already for you.

**Comment by emilioplatzer** [comment]
Thanks. It's good for me.

**Pull request closed without merging**
