### PR TITLE
deps: Update debug due to security issue

### PR DESCRIPTION
**Pull request by danez**
https://nodesecurity.io/advisories/534

### CODE REVIEW

**Comment by dougwilson** [comment]
Also, need an entry in the changelog.

**Comment by danez** [comment]
Ok changed

**Comment by dougwilson** [comment]
Here is an example of previous commits: 53a7b06bc6d90e7a0b3020bfbeea3432aa4fc424 if it helps :)

**Comment by danez** [comment]
Okay removed the version. For the other question I don't know. It also doesn't really matter in my opinion.

**Comment by dougwilson** [comment]
Just remove that sub bullet, then.

**Comment by danez** [comment]
okay thanks.

**Comment by dougwilson** [comment]
I will merge this later today after the Express 4.16 release, as changes here takes away from the CI resources Express.js needs. The number of commits here has sadly created a 30 minute backlog on AppVeyor so Express will be delayed 30 minutes :(

**Pull request closed without merging**
